//
// AnalyticsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class AnalyticsResponse: Codable {

    /** Количество */
    public var result: Int64?


    public init(result: Int64?) {
        self.result = result
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(result, forKey: "result")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                result = try container.decodeIfPresent(Int64.self, forKey: "result")
    }
}

