//
// BatchErrorsModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Объект c информацией ошибкам возникшим при обработке файла */

open class BatchErrorsModel: Codable {

    /** Описание ошибки */
    public var desc: String
    /** Номер строки из файла с данными */
    public var line: Int64
    /** Название столбца с ошибкой */
    public var property: String?


    public init(desc: String, line: Int64, property: String?) {
        self.desc = desc
        self.line = line
        self.property = property
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(desc, forKey: "desc")
        try container.encode(line, forKey: "line")
        try container.encodeIfPresent(property, forKey: "property")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                desc = try container.decode(String.self, forKey: "desc")
                line = try container.decode(Int64.self, forKey: "line")
                property = try container.decodeIfPresent(String.self, forKey: "property")
    }
}

