//
// CardRegisterRequestV2.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос оплаты заказа картой онлайн */

open class CardRegisterRequestV2: Codable {

    /** Идентификатор привзяанной карты, которой нужно оплатить заказ */
    public var bindingId: UUID?
    /** URL, на который происходит перенаправление при нреудачной оплате */
    public var failUrl: String?
    /** URL, на который происходит перенаправление при успешной оплате */
    public var returnUrl: String?


    public init(bindingId: UUID?, failUrl: String?, returnUrl: String?) {
        self.bindingId = bindingId
        self.failUrl = failUrl
        self.returnUrl = returnUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(bindingId, forKey: "bindingId")
        try container.encodeIfPresent(failUrl, forKey: "failUrl")
        try container.encodeIfPresent(returnUrl, forKey: "returnUrl")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                bindingId = try container.decodeIfPresent(UUID.self, forKey: "bindingId")
                failUrl = try container.decodeIfPresent(String.self, forKey: "failUrl")
                returnUrl = try container.decodeIfPresent(String.self, forKey: "returnUrl")
    }
}

