//
// CatalogItemsInShopsQuery.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Объект запроса остатков товаров по магазинам */

open class CatalogItemsInShopsQuery: Codable {

    /** Массив идентификаторов товаров */
    public var itemIds: [UUID]?
    /** Массив идентификаторов магазинов */
    public var shopIds: [UUID]?


    public init(itemIds: [UUID]?, shopIds: [UUID]?) {
        self.itemIds = itemIds
        self.shopIds = shopIds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(itemIds, forKey: "itemIds")
        try container.encodeIfPresent(shopIds, forKey: "shopIds")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                itemIds = try container.decodeIfPresent([UUID].self, forKey: "itemIds")
                shopIds = try container.decodeIfPresent([UUID].self, forKey: "shopIds")
    }
}

