//
// CloudLoyaltyBalance.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class CloudLoyaltyBalance: Codable {

    public var bonuses: [CloudLoyaltyBonuses]?
    public var client: CloudLoyaltyClient?


    public init(bonuses: [CloudLoyaltyBonuses]?, client: CloudLoyaltyClient?) {
        self.bonuses = bonuses
        self.client = client
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(bonuses, forKey: "bonuses")
        try container.encodeIfPresent(client, forKey: "client")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                bonuses = try container.decodeIfPresent([CloudLoyaltyBonuses].self, forKey: "bonuses")
                client = try container.decodeIfPresent(CloudLoyaltyClient.self, forKey: "client")
    }
}

