//
// Collection.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Коллекция */

open class Collection: Codable {

    /** Флаг означающий автоматически импортирована сущность или нет */
    public var _import: Bool?
    /** Ключ коллекции. Ключ может состоять только из цифр, латинских букв в верхнем и нижнем регистре, символов нижнего подчеркивания и тире. */
    public var key: String


    public init(_import: Bool?, key: String) {
        self._import = _import
        self.key = key
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(_import, forKey: "import")
        try container.encode(key, forKey: "key")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                _import = try container.decodeIfPresent(Bool.self, forKey: "import")
                key = try container.decode(String.self, forKey: "key")
    }
}

