//
// CreateVirtual.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос на создание виртуальной карты */

open class CreateVirtual: Codable {

    /** Фамилия */
    public var name: String?
    /** Номер телефона */
    public var phone: String


    public init(name: String?, phone: String) {
        self.name = name
        self.phone = phone
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(name, forKey: "name")
        try container.encode(phone, forKey: "phone")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                name = try container.decodeIfPresent(String.self, forKey: "name")
                phone = try container.decode(String.self, forKey: "phone")
    }
}

