//
// DcBindingRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос привязки карты к пользователю по номеру карты */

open class DcBindingRequest: Codable {

    /** Номер карты */
    public var number: String


    public init(number: String) {
        self.number = number
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(number, forKey: "number")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                number = try container.decode(String.self, forKey: "number")
    }
}

