//
// DcBind.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Модель связи карта-пользователь */

open class DcBind: Codable {

    /** ID компании */
    public var cid: String?
    /** Номер карты */
    public var number: String?
    /** ID пользователя */
    public var uid: String?


    public init(cid: String?, number: String?, uid: String?) {
        self.cid = cid
        self.number = number
        self.uid = uid
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(cid, forKey: "cid")
        try container.encodeIfPresent(number, forKey: "number")
        try container.encodeIfPresent(uid, forKey: "uid")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                cid = try container.decodeIfPresent(String.self, forKey: "cid")
                number = try container.decodeIfPresent(String.self, forKey: "number")
                uid = try container.decodeIfPresent(String.self, forKey: "uid")
    }
}

