//
// DcCardByPhoneConfirmation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class DcCardByPhoneConfirmation: Codable {

    /** Номер телефона (^[0-9]{11,13}$) */
    public var phone: String
    /** Код подтверждения */
    public var code: String


    public init(phone: String, code: String) {
        self.phone = phone
        self.code = code
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(phone, forKey: "phone")
        try container.encode(code, forKey: "code")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                phone = try container.decode(String.self, forKey: "phone")
                code = try container.decode(String.self, forKey: "code")
    }
}

