//
// DcCardMask.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class DcCardMask: Codable {

    /** Номер карты */
    public var number: String
    /** Замаскированный номер телефона к которому привязана карта. Если номер короче 11 символов, то пропорционально сокращать количество выводимых символов 6*2. */
    public var maskPhone: String?


    public init(number: String, maskPhone: String?) {
        self.number = number
        self.maskPhone = maskPhone
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(number, forKey: "number")
        try container.encodeIfPresent(maskPhone, forKey: "maskPhone")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                number = try container.decode(String.self, forKey: "number")
                maskPhone = try container.decodeIfPresent(String.self, forKey: "maskPhone")
    }
}

