//
// FileDeleteRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Объект удаления файла */

open class FileDeleteRequest: Codable {

    /** Полный URL до файла */
    public var fileUrl: String


    public init(fileUrl: String) {
        self.fileUrl = fileUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(fileUrl, forKey: "fileUrl")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                fileUrl = try container.decode(String.self, forKey: "fileUrl")
    }
}

