//
// InviteQuery.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class InviteQuery: Codable {

    /** электронная почта на которую будет выслан инвайт, и которая будет использоваться в качестве логина */
    public var email: String
    public var user: User


    public init(email: String, user: User) {
        self.email = email
        self.user = user
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(email, forKey: "email")
        try container.encode(user, forKey: "user")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                email = try container.decode(String.self, forKey: "email")
                user = try container.decode(User.self, forKey: "user")
    }
}

