//
// OrderV2ListPagination.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class OrderV2ListPagination: Codable {

    public var limit: Int?
    public var offset: Int?
    public var pages: Int?
    public var total: Int?


    public init(limit: Int?, offset: Int?, pages: Int?, total: Int?) {
        self.limit = limit
        self.offset = offset
        self.pages = pages
        self.total = total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(limit, forKey: "limit")
        try container.encodeIfPresent(offset, forKey: "offset")
        try container.encodeIfPresent(pages, forKey: "pages")
        try container.encodeIfPresent(total, forKey: "total")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                limit = try container.decodeIfPresent(Int.self, forKey: "limit")
                offset = try container.decodeIfPresent(Int.self, forKey: "offset")
                pages = try container.decodeIfPresent(Int.self, forKey: "pages")
                total = try container.decodeIfPresent(Int.self, forKey: "total")
    }
}

