//
// OrdersV2StatusShort.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Сокращенный объект статуса заказа */

open class OrdersV2StatusShort: Codable {

    /** Ключ статуса */
    public var key: String?
    /** Человекочитаемое название статуса */
    public var name: String?


    public init(key: String?, name: String?) {
        self.key = key
        self.name = name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(key, forKey: "key")
        try container.encodeIfPresent(name, forKey: "name")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                key = try container.decodeIfPresent(String.self, forKey: "key")
                name = try container.decodeIfPresent(String.self, forKey: "name")
    }
}

