//
// PaymentResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class PaymentResponse: Codable {

    public var orderId: UUID?
    public var success: Bool?


    public init(orderId: UUID?, success: Bool?) {
        self.orderId = orderId
        self.success = success
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(orderId, forKey: "orderId")
        try container.encodeIfPresent(success, forKey: "success")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                orderId = try container.decodeIfPresent(UUID.self, forKey: "orderId")
                success = try container.decodeIfPresent(Bool.self, forKey: "success")
    }
}

