//
// Point.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Объект координат */

open class Point: Codable {

    public var lat: Float
    public var lon: Float


    public init(lat: Float, lon: Float) {
        self.lat = lat
        self.lon = lon
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(lat, forKey: "lat")
        try container.encode(lon, forKey: "lon")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                lat = try container.decode(Float.self, forKey: "lat")
                lon = try container.decode(Float.self, forKey: "lon")
    }
}

