//
// PromocodeItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Объект товара */

open class PromocodeItem: Codable {

    /** Идентификатор товара */
    public var itemId: UUID
    /** Количество товара */
    public var quantity: Int


    public init(itemId: UUID, quantity: Int) {
        self.itemId = itemId
        self.quantity = quantity
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(itemId, forKey: "itemId")
        try container.encode(quantity, forKey: "quantity")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                itemId = try container.decode(UUID.self, forKey: "itemId")
                quantity = try container.decode(Int.self, forKey: "quantity")
    }
}

