//
// ServiceWeekLinked.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Расписание на неделю со связкой магазина и ресурса */

open class ServiceWeekLinked: Codable {

    /** Идентификатор ресурса */
    public var resourceId: UUID?
    /** Идентификатор магазина */
    public var shopId: UUID?
    public var week: ServiceWeek?


    public init(resourceId: UUID?, shopId: UUID?, week: ServiceWeek?) {
        self.resourceId = resourceId
        self.shopId = shopId
        self.week = week
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(resourceId, forKey: "resourceId")
        try container.encodeIfPresent(shopId, forKey: "shopId")
        try container.encodeIfPresent(week, forKey: "week")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                resourceId = try container.decodeIfPresent(UUID.self, forKey: "resourceId")
                shopId = try container.decodeIfPresent(UUID.self, forKey: "shopId")
                week = try container.decodeIfPresent(ServiceWeek.self, forKey: "week")
    }
}

