//
// ServiceOptions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Параметры сервиса */

open class ServiceOptions: Codable {

    /** Продолжительность временного слота в секундах */
    public var timeSlotSize: Double?


    public init(timeSlotSize: Double?) {
        self.timeSlotSize = timeSlotSize
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(timeSlotSize, forKey: "timeSlotSize")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                timeSlotSize = try container.decodeIfPresent(Double.self, forKey: "timeSlotSize")
    }
}

