//
// ServiceDay.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Расписание на день. Work описывает начало и окончания рабочего дня, breaks список перерывов */

open class ServiceDay: Codable {

    public var breaks: [ServiceInterval]?
    public var workTime: ServiceInterval


    public init(breaks: [ServiceInterval]?, workTime: ServiceInterval) {
        self.breaks = breaks
        self.workTime = workTime
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(breaks, forKey: "breaks")
        try container.encode(workTime, forKey: "workTime")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                breaks = try container.decodeIfPresent([ServiceInterval].self, forKey: "breaks")
                workTime = try container.decode(ServiceInterval.self, forKey: "workTime")
    }
}

