//
// ServiceDate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Объект описывающий рабочее время на конкретную дату */

open class ServiceDate: Codable {

    public var breaks: [ServiceInterval]?
    public var workTime: ServiceInterval
    /** Дата по RFC 3339, section 5.6, for example, 2017-07-21 */
    public var date: String


    public init(breaks: [ServiceInterval]?, workTime: ServiceInterval, date: String) {
        self.breaks = breaks
        self.workTime = workTime
        self.date = date
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(breaks, forKey: "breaks")
        try container.encode(workTime, forKey: "workTime")
        try container.encode(date, forKey: "date")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                breaks = try container.decodeIfPresent([ServiceInterval].self, forKey: "breaks")
                workTime = try container.decode(ServiceInterval.self, forKey: "workTime")
                date = try container.decode(String.self, forKey: "date")
    }
}

