//
// SignupQuery.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class SignupQuery: Codable {

    public enum ModelType: String, Codable { 
        case login = "login"
        case email = "email"
    }
    /** Пароль */
    public var password: String
    /** login или email * login - \&quot;^[a-zA-Z]+[a-zA-Z0-9_.-]+$\&quot; (начинается на букву, не менее 2 символов) * email  */
    public var type: ModelType
    /** Логин или электронная почта */
    public var value: String


    public init(password: String, type: ModelType, value: String) {
        self.password = password
        self.type = type
        self.value = value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(password, forKey: "password")
        try container.encode(type, forKey: "type")
        try container.encode(value, forKey: "value")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                password = try container.decode(String.self, forKey: "password")
                type = try container.decode(ModelType.self, forKey: "type")
                value = try container.decode(String.self, forKey: "value")
    }
}

