//
// TransferInput.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Перевод накоплений на виртуальную карту */

open class TransferInput: Codable {

    /** Имя владельца карты */
    public var name: String
    /** Номер другой карты, с которой перенесутся накопления */
    public var oldCard: String
    /** Номер виртуальной карты */
    public var virtualCard: String


    public init(name: String, oldCard: String, virtualCard: String) {
        self.name = name
        self.oldCard = oldCard
        self.virtualCard = virtualCard
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(name, forKey: "name")
        try container.encode(oldCard, forKey: "oldCard")
        try container.encode(virtualCard, forKey: "virtualCard")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                name = try container.decode(String.self, forKey: "name")
                oldCard = try container.decode(String.self, forKey: "oldCard")
                virtualCard = try container.decode(String.self, forKey: "virtualCard")
    }
}

