//
// UserSpace.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Пользовательское пространство */

open class UserSpace: Codable {

    /** Ключ пространства пользователя */
    public var spaceKey: String


    public init(spaceKey: String) {
        self.spaceKey = spaceKey
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(spaceKey, forKey: "spaceKey")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                spaceKey = try container.decode(String.self, forKey: "spaceKey")
    }
}

