//
// AnalyticsPushResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class AnalyticsPushResponse: Codable {

    /** Количество открытых сообщений */
    public var open: Int64?
    /** Количество принятых сообщений */
    public var received: Int64?


    public init(open: Int64?, received: Int64?) {
        self.open = open
        self.received = received
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(open, forKey: "open")
        try container.encodeIfPresent(received, forKey: "received")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                open = try container.decodeIfPresent(Int64.self, forKey: "open")
                received = try container.decodeIfPresent(Int64.self, forKey: "received")
    }
}

