//
// BatchUpdateUsersModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Объект пользователя с обнолвенной информацией и новыми средствами коммуникации */

open class BatchUpdateUsersModel: Codable {

    public var model: UserWithRelations
    /** Список средств коммуникаций, которые необходимо будет подтвердить */
    public var newCommunication: [Communication]?


    public init(model: UserWithRelations, newCommunication: [Communication]?) {
        self.model = model
        self.newCommunication = newCommunication
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(model, forKey: "model")
        try container.encodeIfPresent(newCommunication, forKey: "newCommunication")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                model = try container.decode(UserWithRelations.self, forKey: "model")
                newCommunication = try container.decodeIfPresent([Communication].self, forKey: "newCommunication")
    }
}

