//
// CardIdentification.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос на проверку карты */

open class CardIdentification: Codable {

    /** Номер карты */
    public var cardNumber: String
    /** Фамилия */
    public var name: String?


    public init(cardNumber: String, name: String?) {
        self.cardNumber = cardNumber
        self.name = name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(cardNumber, forKey: "cardNumber")
        try container.encodeIfPresent(name, forKey: "name")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                cardNumber = try container.decode(String.self, forKey: "cardNumber")
                name = try container.decodeIfPresent(String.self, forKey: "name")
    }
}

