//
// CardInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Информация по карте и доступным по ней скидкам */

open class CardInfo: Codable {

    /** Скидка на запчасти в процентах */
    public var catalogDiscount: Double?
    /** Сколько накоплено на этой карте (в рублях) */
    public var saved: Double?
    /** Скидка на сервисы в процентах */
    public var serviceDiscount: Double?


    public init(catalogDiscount: Double?, saved: Double?, serviceDiscount: Double?) {
        self.catalogDiscount = catalogDiscount
        self.saved = saved
        self.serviceDiscount = serviceDiscount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(catalogDiscount, forKey: "catalogDiscount")
        try container.encodeIfPresent(saved, forKey: "saved")
        try container.encodeIfPresent(serviceDiscount, forKey: "serviceDiscount")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                catalogDiscount = try container.decodeIfPresent(Double.self, forKey: "catalogDiscount")
                saved = try container.decodeIfPresent(Double.self, forKey: "saved")
                serviceDiscount = try container.decodeIfPresent(Double.self, forKey: "serviceDiscount")
    }
}

