//
// CloudLoyaltyPagination.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class CloudLoyaltyPagination: Codable {

    /** сколько всего записей */
    public var total: Double


    public init(total: Double) {
        self.total = total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(total, forKey: "total")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                total = try container.decode(Double.self, forKey: "total")
    }
}

