//
// CloudLoyaltyBonuses.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class CloudLoyaltyBonuses: Codable {

    /** количество бонусов */
    public var amount: Double?
    /** дата сгорания бонуса */
    public var expireAt: String?


    public init(amount: Double?, expireAt: String?) {
        self.amount = amount
        self.expireAt = expireAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(amount, forKey: "amount")
        try container.encodeIfPresent(expireAt, forKey: "expireAt")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                amount = try container.decodeIfPresent(Double.self, forKey: "amount")
                expireAt = try container.decodeIfPresent(String.self, forKey: "expireAt")
    }
}

