//
// CommunicationConfirm.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Контакт с пользователем */

open class CommunicationConfirm: Codable {

    public enum ModelType: String, Codable { 
        case email = "email"
        case phone = "phone"
        case androidpushtoken = "androidPushToken"
        case iospushtoken = "iosPushToken"
        case webpushtoken = "webPushToken"
        case vksocial = "vkSocial"
        case fbsocial = "fbSocial"
        case telegram = "telegram"
        case viber = "viber"
    }
    /** Сбрасывать или нет подтверждение у других пользователей */
    public var resetOther: Bool?
    /** Описание типов контактов   * email - по e-mail   * phone - по номеру телефона пользователя   * androidPushToken - по Push Token на операционной системе Android   * iosPushToken - по Push Token на операционной системе IOS   * webPushToken - по Push Token на web платформе   * vkSocial - по уникальному идентификатору пользователя в социальной сети vkontakte   * fbSocial - по уникальному идентификатору пользователя в социальной сети Facebook   * telegram - по уникальному идентификатору пользователя в мессенджере Telegram   * viber - по уникальному идентификатору пользователя в viber  */
    public var type: ModelType
    /** Значение контакта. Например: ivan@hotmail.com */
    public var value: String


    public init(resetOther: Bool?, type: ModelType, value: String) {
        self.resetOther = resetOther
        self.type = type
        self.value = value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(resetOther, forKey: "resetOther")
        try container.encode(type, forKey: "type")
        try container.encode(value, forKey: "value")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                resetOther = try container.decodeIfPresent(Bool.self, forKey: "resetOther")
                type = try container.decode(ModelType.self, forKey: "type")
                value = try container.decode(String.self, forKey: "value")
    }
}

