//
// DcCardImportResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Ответ запроса импорта коллекции карт */

open class DcCardImportResponse: Codable {

    /** Созданны */
    public var created: [DcCardImport]?
    /** С ошибками */
    public var errors: [DcCardImport]?
    /** Обновленны */
    public var updated: [DcCardImport]?


    public init(created: [DcCardImport]?, errors: [DcCardImport]?, updated: [DcCardImport]?) {
        self.created = created
        self.errors = errors
        self.updated = updated
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(created, forKey: "created")
        try container.encodeIfPresent(errors, forKey: "errors")
        try container.encodeIfPresent(updated, forKey: "updated")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                created = try container.decodeIfPresent([DcCardImport].self, forKey: "created")
                errors = try container.decodeIfPresent([DcCardImport].self, forKey: "errors")
                updated = try container.decodeIfPresent([DcCardImport].self, forKey: "updated")
    }
}

