//
// DcCardConfirmation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class DcCardConfirmation: Codable {

    /** Номер карты */
    public var number: String
    /** Код подтверждения */
    public var code: String


    public init(number: String, code: String) {
        self.number = number
        self.code = code
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(number, forKey: "number")
        try container.encode(code, forKey: "code")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                number = try container.decode(String.self, forKey: "number")
                code = try container.decode(String.self, forKey: "code")
    }
}

