//
// DeliveryPrice.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Запрос на цену доставки */

open class DeliveryPrice: Codable {

    /** Название населенного пункта. Передавать точно так же как оно приведено в списке delivery/cities/ */
    public var city: String
    /** Товар в заказе */
    public var items: [ShinOrderItem]


    public init(city: String, items: [ShinOrderItem]) {
        self.city = city
        self.items = items
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(city, forKey: "city")
        try container.encode(items, forKey: "items")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                city = try container.decode(String.self, forKey: "city")
                items = try container.decode([ShinOrderItem].self, forKey: "items")
    }
}

