//
// ErrorModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Объект ошибки */

open class ErrorModel: Codable {

    /** Номер ошибки. Номера ошибок должен составить разработчик серверной части в соответствии с реализацией */
    public var code: Int64
    /** Локализованный объект описания ошибки для показа пользователю или отладки работы системы */
    public var message: Any


    public init(code: Int64, message: Any) {
        self.code = code
        self.message = message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(code, forKey: "code")
        try container.encode(message, forKey: "message")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                code = try container.decode(Int64.self, forKey: "code")
                message = try container.decode(Any.self, forKey: "message")
    }
}

