//
// ExistingUsersModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Объект с обновленной информацией пользователя и номером строки из файла */

open class ExistingUsersModel: Codable {

    public var model: UserWithRelations
    /** Список средств коммуникаций, которые необходимо будет подтвердить */
    public var newCommunication: [Communication]?
    /** Номер строки из файла с данными */
    public var line: Int64?


    public init(model: UserWithRelations, newCommunication: [Communication]?, line: Int64?) {
        self.model = model
        self.newCommunication = newCommunication
        self.line = line
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(model, forKey: "model")
        try container.encodeIfPresent(newCommunication, forKey: "newCommunication")
        try container.encodeIfPresent(line, forKey: "line")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                model = try container.decode(UserWithRelations.self, forKey: "model")
                newCommunication = try container.decodeIfPresent([Communication].self, forKey: "newCommunication")
                line = try container.decodeIfPresent(Int64.self, forKey: "line")
    }
}

