//
// Loyalty.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Объект с данными по лояльности */

open class Loyalty: Codable {

    /** Количество использованных бонусов */
    public var bonuses: Double?
    /** Объект с данными о примененной лояльности */
    public var data: Any?


    public init(bonuses: Double?, data: Any?) {
        self.bonuses = bonuses
        self.data = data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(bonuses, forKey: "bonuses")
        try container.encodeIfPresent(data, forKey: "data")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                bonuses = try container.decodeIfPresent(Double.self, forKey: "bonuses")
                data = try container.decodeIfPresent(Any.self, forKey: "data")
    }
}

