//
// LoyaltyInviteCode.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Объект содержащий код приглашения для карты */

open class LoyaltyInviteCode: Codable {

    /** Код приглашения */
    public var code: String?


    public init(code: String?) {
        self.code = code
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(code, forKey: "code")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                code = try container.decodeIfPresent(String.self, forKey: "code")
    }
}

