//
// OrderExport.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Объект обновления статуса заказа */

open class OrderExport: Codable {

    public var dates: [String]?
    public var ignoreStatus: [String]?
    /** Количество выбираемых элементов, если не задан, или равняется 0 то будут выбраны все элементы начиная с offset */
    public var limit: Int64?
    /** Смещение от начала выборки */
    public var offset: Int64?


    public init(dates: [String]?, ignoreStatus: [String]?, limit: Int64?, offset: Int64?) {
        self.dates = dates
        self.ignoreStatus = ignoreStatus
        self.limit = limit
        self.offset = offset
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(dates, forKey: "dates")
        try container.encodeIfPresent(ignoreStatus, forKey: "ignore_status")
        try container.encodeIfPresent(limit, forKey: "limit")
        try container.encodeIfPresent(offset, forKey: "offset")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                dates = try container.decodeIfPresent([String].self, forKey: "dates")
                ignoreStatus = try container.decodeIfPresent([String].self, forKey: "ignore_status")
                limit = try container.decodeIfPresent(Int64.self, forKey: "limit")
                offset = try container.decodeIfPresent(Int64.self, forKey: "offset")
    }
}

