//
// PasswordQuery.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class PasswordQuery: Codable {

    public enum ModelType: String, Codable { 
        case login = "login"
        case email = "email"
        case phone = "phone"
    }
    public var password: String
    /** Тип value: login, email или phone   * login - \&quot;^[a-zA-Z]+[a-zA-Z0-9_.-]+$\&quot; (начинается на букву, не менее 2 символов)   * phone - \&quot;^[0-9]{11,13}$\&quot; (только числа от 11 до 13 символов)   * email  */
    public var type: ModelType
    /** Login (must begin with a letter, two or more characters) or email (email regular) or phone (only numbers) */
    public var value: String


    public init(password: String, type: ModelType, value: String) {
        self.password = password
        self.type = type
        self.value = value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(password, forKey: "password")
        try container.encode(type, forKey: "type")
        try container.encode(value, forKey: "value")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                password = try container.decode(String.self, forKey: "password")
                type = try container.decode(ModelType.self, forKey: "type")
                value = try container.decode(String.self, forKey: "value")
    }
}

