//
// ServiceInterval.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Временной интервал. Время указывается в секундах от полуночи. */

open class ServiceInterval: Codable {

    /** Начало интервала. */
    public var begin: Double
    /** Окончание интервала. */
    public var end: Double


    public init(begin: Double, end: Double) {
        self.begin = begin
        self.end = end
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(begin, forKey: "begin")
        try container.encode(end, forKey: "end")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                begin = try container.decode(Double.self, forKey: "begin")
                end = try container.decode(Double.self, forKey: "end")
    }
}

