//
// ShopGroupWithRelations.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Магазин с дополнительными свойствами */

open class ShopGroupWithRelations: Codable {

    /** Идентификатор */
    public var id: UUID?
    /** Флаг означающий автоматически импортирована сущность или нет */
    public var _import: Bool?
    public var location: Point?
    /** Название группы */
    public var name: String
    /** Идентификатор родительской группы */
    public var parent: UUID?
    /** Cписок основан на базе данных временных https://www.iana.org/time-zones (https://tools.ietf.org/html/rfc6557) */
    public var timezone: String?
    /** Условный вес элемента. Используется при сортировке — чем больше это значение, тем выше элемент в выборке */
    public var weight: Int?
    public var properties: [IPropertyValue]?


    public init(id: UUID?, _import: Bool?, location: Point?, name: String, parent: UUID?, timezone: String?, weight: Int?, properties: [IPropertyValue]?) {
        self.id = id
        self._import = _import
        self.location = location
        self.name = name
        self.parent = parent
        self.timezone = timezone
        self.weight = weight
        self.properties = properties
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(id, forKey: "id")
        try container.encodeIfPresent(_import, forKey: "import")
        try container.encodeIfPresent(location, forKey: "location")
        try container.encode(name, forKey: "name")
        try container.encodeIfPresent(parent, forKey: "parent")
        try container.encodeIfPresent(timezone, forKey: "timezone")
        try container.encodeIfPresent(weight, forKey: "weight")
        try container.encodeIfPresent(properties, forKey: "properties")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                id = try container.decodeIfPresent(UUID.self, forKey: "id")
                _import = try container.decodeIfPresent(Bool.self, forKey: "import")
                location = try container.decodeIfPresent(Point.self, forKey: "location")
                name = try container.decode(String.self, forKey: "name")
                parent = try container.decodeIfPresent(UUID.self, forKey: "parent")
                timezone = try container.decodeIfPresent(String.self, forKey: "timezone")
                weight = try container.decodeIfPresent(Int.self, forKey: "weight")
                properties = try container.decodeIfPresent([IPropertyValue].self, forKey: "properties")
    }
}

