//
// StatisticsEventOrderItems.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Событие изменения состава заказа */

open class StatisticsEventOrderItems: Codable {

    /** Идентификатор объекта заказа */
    public var id: String
    /** Состав заказа */
    public var newValue: [StatisticsOrderItem]
    /** Идентификатор владельца заказа */
    public var uid: String


    public init(id: String, newValue: [StatisticsOrderItem], uid: String) {
        self.id = id
        self.newValue = newValue
        self.uid = uid
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(id, forKey: "id")
        try container.encode(newValue, forKey: "newValue")
        try container.encode(uid, forKey: "uid")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                id = try container.decode(String.self, forKey: "id")
                newValue = try container.decode([StatisticsOrderItem].self, forKey: "newValue")
                uid = try container.decode(String.self, forKey: "uid")
    }
}

