//
// SupportOperatorShort.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Оператор, короткая мобель без средств связи */

open class SupportOperatorShort: Codable {

    /** Идентификатор */
    public var id: UUID?
    /** Имя оператора */
    public var name: String?
    public var properties: [IPropertyValue]?


    public init(id: UUID?, name: String?, properties: [IPropertyValue]?) {
        self.id = id
        self.name = name
        self.properties = properties
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(id, forKey: "id")
        try container.encodeIfPresent(name, forKey: "name")
        try container.encodeIfPresent(properties, forKey: "properties")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                id = try container.decodeIfPresent(UUID.self, forKey: "id")
                name = try container.decodeIfPresent(String.self, forKey: "name")
                properties = try container.decodeIfPresent([IPropertyValue].self, forKey: "properties")
    }
}

