//
// SupportFeedback.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Объект запроса отправить отзыв. Обязательно должен быть указан phone или email */

open class SupportFeedback: Codable {

    /** Сообщение */
    public var comment: String
    public var email: String?
    /** Имя пользователя */
    public var name: String
    public var phone: String?


    public init(comment: String, email: String?, name: String, phone: String?) {
        self.comment = comment
        self.email = email
        self.name = name
        self.phone = phone
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(comment, forKey: "comment")
        try container.encodeIfPresent(email, forKey: "email")
        try container.encode(name, forKey: "name")
        try container.encodeIfPresent(phone, forKey: "phone")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                comment = try container.decode(String.self, forKey: "comment")
                email = try container.decodeIfPresent(String.self, forKey: "email")
                name = try container.decode(String.self, forKey: "name")
                phone = try container.decodeIfPresent(String.self, forKey: "phone")
    }
}

