//
// TalanRefreshQuery.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class TalanRefreshQuery: Codable {

    public enum ModelType: String, Codable { 
        case phone = "phone"
        case email = "email"
    }
    public var appType: String
    /** * phone - \&quot;^[0-9]{11,13}$\&quot; (только числа от 11 до 13 символов) * email - \&quot;(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$)\&quot;  */
    public var type: ModelType
    /** Идентификатор пользователя */
    public var uid: String
    /** Телефон или электронная почта */
    public var value: String


    public init(appType: String, type: ModelType, uid: String, value: String) {
        self.appType = appType
        self.type = type
        self.uid = uid
        self.value = value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(appType, forKey: "appType")
        try container.encode(type, forKey: "type")
        try container.encode(uid, forKey: "uid")
        try container.encode(value, forKey: "value")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                appType = try container.decode(String.self, forKey: "appType")
                type = try container.decode(ModelType.self, forKey: "type")
                uid = try container.decode(String.self, forKey: "uid")
                value = try container.decode(String.self, forKey: "value")
    }
}

