//
// UserQuery.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Объект запроса пользователей */

open class UserQuery: Codable {

    public enum Order: String, Codable { 
        case desc = "DESC"
        case asc = "ASC"
    }
    /** Список идентификаторов пользователей. При наличии опускаются правила фильтрации query */
    public var ids: [String]?
    /** Количество выбираемых элементов */
    public var limit: Int64?
    /** Смещение от начала выборки */
    public var offset: Int64?
    /** Порядок сортировки по полю указанному в orderBy #описание порядка сортировки    * ASC - сортировка по возрастанию (прямой порядок)   * DESC - сортировка по убыванию (обратный порядок)  */
    public var order: Order?
    /** По какому полю должна происходить сортировка. */
    public var orderBy: String?
    /** Строка для поиска по тексту по полям login, firstName, lastName, middleName */
    public var query: String?


    public init(ids: [String]?, limit: Int64?, offset: Int64?, order: Order?, orderBy: String?, query: String?) {
        self.ids = ids
        self.limit = limit
        self.offset = offset
        self.order = order
        self.orderBy = orderBy
        self.query = query
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(ids, forKey: "ids")
        try container.encodeIfPresent(limit, forKey: "limit")
        try container.encodeIfPresent(offset, forKey: "offset")
        try container.encodeIfPresent(order, forKey: "order")
        try container.encodeIfPresent(orderBy, forKey: "orderBy")
        try container.encodeIfPresent(query, forKey: "query")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                ids = try container.decodeIfPresent([String].self, forKey: "ids")
                limit = try container.decodeIfPresent(Int64.self, forKey: "limit")
                offset = try container.decodeIfPresent(Int64.self, forKey: "offset")
                order = try container.decodeIfPresent(Order.self, forKey: "order")
                orderBy = try container.decodeIfPresent(String.self, forKey: "orderBy")
                query = try container.decodeIfPresent(String.self, forKey: "query")
    }
}

