//
// VirtualCard.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Описание виртуальной карты */

open class VirtualCard: Codable {

    /** Номер карты */
    public var cardNumber: String?
    /** Создана карта, или нет */
    public var isCreated: Bool?
    /** Верифицирована или нет(верефицированная сразу считается активной) */
    public var isVerified: Bool?
    /** Фамилия */
    public var name: String?


    public init(cardNumber: String?, isCreated: Bool?, isVerified: Bool?, name: String?) {
        self.cardNumber = cardNumber
        self.isCreated = isCreated
        self.isVerified = isVerified
        self.name = name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(cardNumber, forKey: "cardNumber")
        try container.encodeIfPresent(isCreated, forKey: "isCreated")
        try container.encodeIfPresent(isVerified, forKey: "isVerified")
        try container.encodeIfPresent(name, forKey: "name")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                cardNumber = try container.decodeIfPresent(String.self, forKey: "cardNumber")
                isCreated = try container.decodeIfPresent(Bool.self, forKey: "isCreated")
                isVerified = try container.decodeIfPresent(Bool.self, forKey: "isVerified")
                name = try container.decodeIfPresent(String.self, forKey: "name")
    }
}

