//
// WeekWorkTime.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Объект содержащий рабочее время на неделю */

open class WeekWorkTime: Codable {

    public var fr: WorkTime?
    public var mo: WorkTime?
    public var sa: WorkTime?
    public var su: WorkTime?
    public var th: WorkTime?
    public var tu: WorkTime?
    public var we: WorkTime?


    public init(fr: WorkTime?, mo: WorkTime?, sa: WorkTime?, su: WorkTime?, th: WorkTime?, tu: WorkTime?, we: WorkTime?) {
        self.fr = fr
        self.mo = mo
        self.sa = sa
        self.su = su
        self.th = th
        self.tu = tu
        self.we = we
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(fr, forKey: "fr")
        try container.encodeIfPresent(mo, forKey: "mo")
        try container.encodeIfPresent(sa, forKey: "sa")
        try container.encodeIfPresent(su, forKey: "su")
        try container.encodeIfPresent(th, forKey: "th")
        try container.encodeIfPresent(tu, forKey: "tu")
        try container.encodeIfPresent(we, forKey: "we")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

                fr = try container.decodeIfPresent(WorkTime.self, forKey: "fr")
                mo = try container.decodeIfPresent(WorkTime.self, forKey: "mo")
                sa = try container.decodeIfPresent(WorkTime.self, forKey: "sa")
                su = try container.decodeIfPresent(WorkTime.self, forKey: "su")
                th = try container.decodeIfPresent(WorkTime.self, forKey: "th")
                tu = try container.decodeIfPresent(WorkTime.self, forKey: "tu")
                we = try container.decodeIfPresent(WorkTime.self, forKey: "we")
    }
}

